### ISSUE TITLE
Kosovo is missing in Europe map

### ISSUE THREAD

**Issue by dwaxweiler** [tenpages/us-level#22]
Hello,
What a fun tool!
Could you add [Kosovo](https://en.wikipedia.org/wiki/Kosovo) please?
Kind regards,
Daniel

**Comment by yamaha252** [comment]
And Gibraltar 😄

**Comment by tenpages** [comment]
see https://github.com/tenpages/us-level/issues/4#issuecomment-1291184947 and https://github.com/tenpages/us-level/blob/17d6d507e1d86bbc4f70ce408147844df0376fa5/README.md?plain=1#L32

**Comment by dwaxweiler** [comment]
Thanks for your quick reply, @tenpages!

Just to be clear: Kosovo is recognized by a majority of countries in the world. You find more details here: https://en.wikipedia.org/wiki/International_recognition_of_Kosovo
