### ISSUE TITLE
What's the difference between "stayed here" and "visited here"

### ISSUE THREAD

**Issue by technicallyty** [tenpages/us-level#31]
Kinda seems like the same thing. Would be nice to have a little tooltip to explain each option.

**Comment by tvanantwerp** [comment]
I'm also confused by this.

**Comment by alix-tz** [comment]
Hi! I was confused by this too, but if you check the README of the world map version (see #18) (and use a little help to translate), you can find that:
- "stayed there" means you stayed for a 1 month long trip (at least)
- whereas "visited here" means that you travelled there

**Comment by tenpages** [comment]
Discussed [here](https://github.com/tenpages/us-level/issues/7#issuecomment-1292828407).
