### ISSUE TITLE
Include Gibraltar in EU map

### ISSUE THREAD

**Issue by PeaSeaGee** [tenpages/us-level#4]
Other euro microstates are included, Gibraltar should be as well.

**Comment by tenpages** [comment]
Gibraltar is not a sovereign country - the same reason for not adding Scotland, Catalonia, Mann, etc. Other states that are not overwhelmingly recognized by other countries are also not included. I understand that it would cause frustration for either some people or some other people, no matter how I choose to set a standard. But it is just a toy app for fun and I had to do it somehow.

Anyway, feel free to fork and create your own version. I'll add a disclaimer in README.
