### ISSUE TITLE
Persistent storage?

### ISSUE THREAD

**Issue by bobpaul** [tenpages/us-level#5]
It would be nice if the statuses were saved locally (`indexdb` maybe?) so that if I visit the site tomorrow on the same device, it still has everything I filled in. I do see there's an object in `localStorage` that seems to represent the map statuses, but it doesn't look like that's saved to disk and it disappears if I close the browser tab.

**Comment by tenpages** [comment]
Thanks for pointing that out - the original code I have had a local-storage function but I could seem to get it to work. I'll look into that again when I am less busy a while later - or if you would like to contribute feel free to!

**Comment by bobpaul** [comment]
This ended up being really easy. Localstorage was working correctly, but the app was rejecting the value it found. I think at one point you were only tracking 34 provinces but the current version handles 56 states/territories in the US and 49 countries in the EU.

**Comment by tenpages** [comment]
> This ended up being really easy. Localstorage was working correctly, but the app was rejecting the value it found. I think at one point you were only tracking 34 provinces but the current version handles 56 states/territories in the US and 49 countries in the EU.

fixed after https://github.com/tenpages/us-level/commit/3222341dc1186e2e88a556ad376be2573a9d4a7c
