### ISSUE TITLE
Clarify "Stayed here"

### ISSUE THREAD

**Issue by ericlaw1979** [tenpages/us-level#8]
Everyone asks "What does "Stayed here" means. A single overnight stay? Multiple? etc.

**Comment by ericlaw1979** [comment]
I guess this is technically the same as #7 which was WONTFIX. The problem here is that this thing is inherently social, and if it's ambiguous, there's overhead from everyone asking and fretting to get a shared understanding of what things mean. That takes away from the joy.

**Comment by ericlaw1979** [comment]
Even if you wanted to change the UX to something as simple as "Stayed Here (2d+)" that would be a solid fix.

**Comment by aenayef** [comment]
Hope my interpretation below helps, and thx for the App.
Tried to match score with duration for simplicity.

Lived here (> 5 months) 
Stayed here (> 4 weeks) [as in temporarily lived here]
Visited here (> 3 days) [Conference, Visit, …]
Stopped here (> 2 meals, ~6hrs or a day)
Passed here (> 1 hour) [as in drove by, or connecting flight, …]

**Comment by tenpages** [comment]
See #7
