### ISSUE TITLE
EU != Europe

### ISSUE THREAD

**Issue by nahkampf** [tenpages/us-level#9]
The headline "EU level" should probably read "*Europe level*". The follow states on your map are *not* EU members:

- Russia
- Belarus
- Ukraine
- Georgia
- Azerbaijan
- Armenia
- Turkey
- Albania
- Iceland
- Norway
- Lichtenstein
- Switzerland
- Montenegro
- North Macedonia
- Serbia
- Bosnia and Herzegovina
- Moldova
- Andorra
- San Marino
- United Kingdom

**Comment by tenpages** [comment]
fixed https://github.com/tenpages/us-level/commit/2837f1473ed72b7a4702dec5c8b1996cd5ac1db1
